## Comprehensive Numpy Usage & Examples ##

In [1]:
import numpy as np

#### Creation ####

In [14]:
a = np.array([[1,2],[3,4]])
print(type(a))
print(type(a[0]))
b = np.array([1,2,3,4], ndmin=2)
b

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([[1, 2, 3, 4]])

In [38]:
'''
numpy.empty(shape, dtype = float, order = 'C')
'''
a = np.empty((2, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
'''
numpy.zeros(shape, dtype = float, order = 'C')
numpy.ones(shape, dtype = None, order = 'C')
'''

#### Attributes ####

In [35]:
# shape
b.shape

(2, 2)

In [18]:
b.shape = (2,2) # equivalent to reshape
b

array([[1, 2],
       [3, 4]])

In [26]:
# ndim
a = np.arange(6)
print(a)
a = a.reshape((2, 3, 1))
a.ndim

[0 1 2 3 4 5]


3

In [27]:
# itemsize
a.itemsize

8

In [34]:
# flags
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

#### Changing Shape ####

In [32]:
"""
numpy.reshape(arr, newshape, order')
    arr: Array to be reshaped
    newshape: int or tuple of int. New shape should be compatible to the original shape
    order: 'C' for C style, 'F' for Fortran style, 'A' means Fortran like order if an array is stored in Fortran-like contiguous memory, C style otherwise
"""
a = np.arange(8)
print('orginal array\n', a)
b = np.reshape(a, (4,2))
print('reshaped array\n', b)
c = b.reshape((2,4,1))
print('reshaped array\n', c)
b.reshape((4,-1))

orginal array
 [0 1 2 3 4 5 6 7]
reshaped array
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
reshaped array
 [[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
"""
np.ndarray.flat
    This function returns a 1-D iterator over the array. It behaves similar to Python's built-in iterator.
"""
print('original array\n', c)
flat_array = c.flat
print('flattened array\n', np.array(flat_array))

original array
 [[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]
flattened array
 [0 1 2 3 4 5 6 7]


In [22]:
"""
ndarray.flatten(order)
    This function returns a copy of an array collapsed into one dimension. 
    order: see reshape
"""
flattened_array = c.flatten()
flattened_array[0] = 1000
print(c)

[[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]


In [26]:
"""
numpy.ravel(a, order)
    This function returns a flattened one-dimensional array. 
    A copy is made only if needed. 
    The returned array will have the same type as that of the input array. 
"""
ravelled_array = c.ravel()
ravelled_array[0] = 1000
print(c)
# difference between flatten & ravel():
# flatten always return a copy, ravel may not
# ie whether modifying array changes original array

[[[1000]
  [   1]
  [   2]
  [   3]]

 [[   4]
  [   5]
  [   6]
  [   7]]]


#### Transpose Operations ####

In [40]:
"""
numpy.transpose(arr, axes)
    axes: List of ints, corresponding to the dimensions. By default, the dimensions are reversed
"""
a = np.arange(12).reshape((3,4,1))
print('original\n', a)
a_t = np.transpose(a, axes=[2,1,0])
print('transposed\n', a_t)

original
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
transposed
 [[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]]


In [41]:
"""
numpy.ndarray.T
    This function belongs to ndarray class. It behaves similar to numpy.transpose.
"""
a.T

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]])

In [49]:
"""
numpy.rollaxis(arr, axis, start)
    This function rolls the specified axis backwards, until it lies in a specified position. 
    axis: Axis to roll backwards. The position of the other axes do not change relative to one another
    start: Zero by default leading to the complete roll. Rolls until it reaches the specified position
"""
a = np.ones((3,4,5,6))
print('orginal\n', a.shape)
rolled = np.rollaxis(a, 3, 1)
print('rolled\n', rolled.shape)


orginal
 (3, 4, 5, 6)
rolled
 (3, 6, 4, 5)


In [50]:
"""
numpy.swapaxes(arr, axis1, axis2)
    This function interchanges the two axes of an array.
"""
a = np.ones((2,3,4,6))
print('original', a.shape)
b = np.swapaxes(a, 0, 3)
print('swapped', b.shape)

original (2, 3, 4, 6)
swapped (6, 3, 4, 2)


#### Changing Dimensions ####

#### Array Manipulation ####

In [39]:
""" 
numpy.concatenate((a1, a2, ...), axis)
    (a1, a2, ...): Sequence of arrays of the same type
    axis: Axis along which arrays have to be joined. Default is 0
"""
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11, 12]])
join_list = [a, b, c]
print('axis=0 concatenation')
print(np.concatenate(join_list, axis=0))
print('axis=1 concatenation')
print(np.concatenate(join_list, axis=1))

axis=0 concatenation
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
axis=1 concatenation
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [38]:
d = np.array([[[1],[2]],[[3],[4]]])
e = np.array([[[5],[6]],[[7],[8]]])
print('axis0\n', np.concatenate((d, e), axis=0))
print('axis1\n', np.concatenate((d, e), axis=1))
print('axis2\n', np.concatenate((d, e), axis=2))

axis0
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
axis1
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
axis2
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [37]:
"""
numpy.stack(arrays, axis)
    arrays: Sequence of arrays of the same shape
    axis: Axis in the resultant array along which the input arrays are stacked
"""
stack_list = [a, b, c]
print("axis0\n", np.stack(stack_list, axis=0))
print("axis1\n", np.stack(stack_list, axis=1))

axis0
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
axis1
 [[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]


In [54]:
"""
numpy.hstack
    Variants of numpy.stack function to stack so as to make a single array horizontally.
"""
(np.hstack((a,b,c)) != np.concatenate((a,b,c), axis=1)).sum().sum() == 0
# same as concatenate axis=1

True

In [57]:
"""
numpy.vstack
    Variants of numpy.stack function to stack so as to make a single array vertically.
"""
(np.vstack((a,b,c)) != np.concatenate((a,b,c), axis=0)).sum().sum() == 0
# same as concatenate axis=0

True