## Comprehensive Numpy Usage & Examples ##

In [1]:
import numpy as np

#### Changing Shape ####

In [ ]:
"""

"""

#### Array Manipulation ####

In [39]:
""" 
numpy.concatenate((a1, a2, ...), axis)
    (a1, a2, ...): Sequence of arrays of the same type
    axis: Axis along which arrays have to be joined. Default is 0
"""
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11, 12]])
join_list = [a, b, c]
print('axis=0 concatenation')
print(np.concatenate(join_list, axis=0))
print('axis=1 concatenation')
print(np.concatenate(join_list, axis=1))

axis=0 concatenation
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
axis=1 concatenation
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [38]:
d = np.array([[[1],[2]],[[3],[4]]])
e = np.array([[[5],[6]],[[7],[8]]])
print('axis0\n', np.concatenate((d, e), axis=0))
print('axis1\n', np.concatenate((d, e), axis=1))
print('axis2\n', np.concatenate((d, e), axis=2))

axis0
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
axis1
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
axis2
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [37]:
"""
numpy.stack(arrays, axis)
    arrays: Sequence of arrays of the same shape
    axis: Axis in the resultant array along which the input arrays are stacked
"""
stack_list = [a, b, c]
print("axis0\n", np.stack(stack_list, axis=0))
print("axis1\n", np.stack(stack_list, axis=1))

axis0
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
axis1
 [[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]


In [54]:
"""
numpy.hstack
    Variants of numpy.stack function to stack so as to make a single array horizontally.
"""
(np.hstack((a,b,c)) != np.concatenate((a,b,c), axis=1)).sum().sum() == 0
# same as concatenate axis=1

True

In [57]:
"""
numpy.vstack
    Variants of numpy.stack function to stack so as to make a single array vertically.
"""
(np.vstack((a,b,c)) != np.concatenate((a,b,c), axis=0)).sum().sum() == 0
# same as concatenate axis=0

True