In [1]:
import pandas as pd
import numpy as np

In [3]:
# series: 1 dim (size immutable)
# dataframe: 2 dim
# panel: 3 dim

### Series ###

In [13]:
"""
pd.Series(data, index, dtype, copy)
    data: data takes various forms like ndarray, list, constants
    index: Index values must be unique and hashable, same length as data. 
           Default np.arrange(n) if no index is passed.
    dtype: dtype is for data type. If None, data type will be inferred
    copy: Copy data. Default False
"""
s = pd.Series(dtype=object)
s

Series([], dtype: object)

In [23]:
# from numpy array
data = np.array(['a', 'b', 'c', 'd'])
s = pd.Series(data)
print(s)
s = pd.Series(data, index=[100, 101, 102, 103])
print(s)

0    a
1    b
2    c
3    d
dtype: object
100    a
101    b
102    c
103    d
dtype: object


In [42]:
data = np.array([1.1, 2.2, 3.3, 4.4]) # ??? only affects np.array non string
s = pd.Series(data, copy=False)
s.iloc[0] = 10.2
print(s)
print(data)

0    10.2
1     2.2
2     3.3
3     4.4
dtype: float64
[10.2  2.2  3.3  4.4]


In [50]:
# from dictionary
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data) # keys are used to construct index
print(s)
s = pd.Series(data, index=['a', 'b', 'c', 'd']) # index order preserved
print(s)

a    0.0
b    1.0
c    2.0
dtype: float64
a    0.0
b    1.0
c    2.0
d    NaN
dtype: float64


In [52]:
# from scalar
s = pd.Series(5, index=[0, 1, 2, 3])
s # the value will be repeated to match the length of index

0    5
1    5
2    5
3    5
dtype: int64

In [58]:
# accessing data
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s[1])
print(s[:3])
print(s[-3:])
print(s['d'])
print(s[['a', 'c', 'd']])


2
a    1
b    2
c    3
dtype: int64
c    3
d    4
e    5
dtype: int64
4
a    1
c    3
d    4
dtype: int64


### DataFrame ###

In [2]:
''' 
pandas.DataFrame(data, index, columns, dtype, copy)
    data: ndarray, series, map, lists, dict, constants
    index: row labels
'''

' \npandas.DataFrame(data, index, columns, dtype, copy)\n    data: ndarray, series, map, lists, dict, constants\n    index: row labels\n'

In [6]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [12]:
# create df from list
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df) # deprecated

   0
0  1
1  2
2  3
3  4
4  5
     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13
     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


/Users/phichitchulanont/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3267: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)


In [13]:
# create df from Dict of ndarrays / Lists
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
df

Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42

In [20]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]} # each dic is a column
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
df

Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42

In [21]:
# create df from list of dicts
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}] # each dic is a row
df = pd.DataFrame(data)
df

a   b     c
0  1   2   NaN
1  5  10  20.0

In [22]:
# seet index
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, index=['first', 'second'])
df

a   b     c
first   1   2   NaN
second  5  10  20.0

In [24]:
# create df from Dic of Series
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [25]:
# select column
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [30]:
# column addition
df['three'] = df['one'] + df['two']
df

one  two  three
a  1.0    1    2.0
b  2.0    2    4.0
c  3.0    3    6.0
d  NaN    4    NaN

In [31]:
# column deletion
del df['three']
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [33]:
df.pop('two')
df

one
a  1.0
b  2.0
c  3.0
d  NaN

In [35]:
# row selection, addition, and deletion
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [41]:
print(type(df.loc['b']))
df.loc['b']

<class 'pandas.core.series.Series'>


one    2.0
two    2.0
Name: b, dtype: float64

In [42]:
df.iloc[2]

one    3.0
two    3.0
Name: c, dtype: float64

In [43]:
# slice rows
df[2:4]

one  two
c  3.0    3
d  NaN    4

In [12]:
# addition
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])
df = df.append(df2)
df

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [13]:
print(df.index)
df = df.drop(index=0)
print(df.index)
df

Int64Index([0, 1, 0, 1], dtype='int64')
Int64Index([1, 1], dtype='int64')


a  b
1  3  4
1  7  8

### Panel ###

In [19]:
print(pd.__version__)
# panel has been removed

1.3.1


In [ ]:
# pandas.Panel(data, items, major_axis, minor_axis, dtype, copy)
# deprecated

In [20]:
data = np.random.rand(2,4,5)
print(data)
#p = pd.Panel(data)

[[[0.88734208 0.06838684 0.85097435 0.06880823 0.50740681]
  [0.53391734 0.48904843 0.80451022 0.19523583 0.98792353]
  [0.88117797 0.96723983 0.57660127 0.86192481 0.89825808]
  [0.0839457  0.4874043  0.31584979 0.90837376 0.402868  ]]

 [[0.49019733 0.97867174 0.59028147 0.58462989 0.54630031]
  [0.56666222 0.70302267 0.05812085 0.88207743 0.48650731]
  [0.2712874  0.91200067 0.5440278  0.81565483 0.03874466]
  [0.91817501 0.35323288 0.79801686 0.24815126 0.23603052]]]


### Basic Functionality ###

In [2]:
s = pd.Series(np.random.randn(4))

In [5]:
print("axes\n", s.axes)
print("dtype\n", s.dtype)
print("empty\n", s.empty)
print("ndim\n", s.ndim)
print("size\n", s.size)
print("values\n", s.values)
print("head\n", s.head())
print("tail\n", s.tail())

axes
 [RangeIndex(start=0, stop=4, step=1)]
dtype
 float64
empty
 False
ndim
 1
size
 4
values
 [ 0.06504169 -1.02060985  0.21459751  0.70705839]
head
 0    0.065042
1   -1.020610
2    0.214598
3    0.707058
dtype: float64
tail
 0    0.065042
1   -1.020610
2    0.214598
3    0.707058
dtype: float64


In [9]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}
df = pd.DataFrame(d)
df.dtypes

Name       object
Age         int64
Rating    float64
dtype: object

In [10]:
df.T

0      1      2     3      4      5     6
Name     Tom  James  Ricky   Vin  Steve  Smith  Jack
Age       25     26     25    23     30     29    23
Rating  4.23   3.24   3.98  2.56    3.2    4.6   3.8

### Descriptive Statistics ###

In [11]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}

df = pd.DataFrame(d)

In [13]:
df.sum()

Name      TomJamesRickyVinSteveSmithJackLeeDavidGasperBe...
Age                                                     382
Rating                                                44.92
dtype: object

In [15]:
df.sum(axis=1, numeric_only=True)

0     29.23
1     29.24
2     28.98
3     25.56
4     33.20
5     33.60
6     26.80
7     37.78
8     42.98
9     34.80
10    55.10
11    49.65
dtype: float64

In [19]:
"""
count()
sum()
mean()
median()
mode()
std()
min()
max()
abs()
prod(): product of values
cumsum(): cumulative sum
cumprod(): cumulative product
"""

'\ncount()\nsum()\nmean()\nmedian()\nmode()\nstd()\nmin()\nmax()\nabs()\nprod(): product of values\ncumsum(): cumulative sum\ncumprod(): cumulative product\n'

In [23]:
# summarizing data
# df.describe() # excludes character column
df.describe(include=['object']) # just Name

Name
count    12
unique   12
top     Tom
freq      1

In [24]:
df.describe(include='all')

Name        Age     Rating
count    12  12.000000  12.000000
unique   12        NaN        NaN
top     Tom        NaN        NaN
freq      1        NaN        NaN
mean    NaN  31.833333   3.743333
std     NaN   9.232682   0.661628
min     NaN  23.000000   2.560000
25%     NaN  25.000000   3.230000
50%     NaN  29.500000   3.790000
75%     NaN  35.500000   4.132500
max     NaN  51.000000   4.800000

### Function Application ###

Table wise function application: pipe() <br>
Row or Column wise function application: apply() <br>
Element wise function application: applymap() <br>

In [6]:
# table-wise
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['col1','col2','col3'])
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [12]:
def adder(m, n, p):
    return m + n - p
df.pipe(adder, 2, 3)
#df.pipe(lambda x : x+2) # add 2 to each cell

col1  col2  col3
0     0     1     2
1     3     4     5
2     6     7     8

In [13]:
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [20]:
# row/column wise
# row: axis=1, column: axis=0
df.apply(np.mean) # mean of columns

col1    4.0
col2    5.0
col3    6.0
dtype: float64

In [16]:
df.apply(np.mean, axis=1) # mean of rows

0    2.0
1    5.0
2    8.0
dtype: float64

In [21]:
df.apply(lambda x : x.max() - x.min(), axis=1)

0    2
1    2
2    2
dtype: int64

In [23]:
# element-wise
df['col1'].map(str)

0    1
1    4
2    7
Name: col1, dtype: object

### Reindexing ###
Changes the row labels and columns labels. 

In [25]:
N=20

df = pd.DataFrame({
   'A': pd.date_range(start='2016-01-01',periods=N,freq='D'),
   'x': np.linspace(0,stop=N-1,num=N),
   'y': np.random.rand(N),
   'C': np.random.choice(['Low','Medium','High'],N).tolist(),
   'D': np.random.normal(100, 10, size=(N)).tolist()
})
df

A     x         y       C           D
0  2016-01-01   0.0  0.873822    High  103.361889
1  2016-01-02   1.0  0.416533  Medium  106.629000
2  2016-01-03   2.0  0.435559     Low   98.477243
3  2016-01-04   3.0  0.439431    High   96.107612
4  2016-01-05   4.0  0.481112     Low   99.827981
5  2016-01-06   5.0  0.154059    High  116.755378
6  2016-01-07   6.0  0.036748    High   82.744792
7  2016-01-08   7.0  0.392114     Low  111.885502
8  2016-01-09   8.0  0.716958  Medium  110.589856
9  2016-01-10   9.0  0.205751  Medium  113.043914
10 2016-01-11  10.0  0.322804    High  115.675756
11 2016-01-12  11.0  0.474384     Low  102.459813
12 2016-01-13  12.0  0.308507  Medium  100.142202
13 2016-01-14  13.0  0.828070  Medium   95.902893
14 2016-01-15  14.0  0.328733     Low  105.424876
15 2016-01-16  15.0  0.122427    High  110.136888
16 2016-01-17  16.0  0.527552    High   90.923405
17 2016-01-18  17.0  0.726843  Medium  111.709191
18 2016-01-19  18.0  0.894948    High   99.828281
19 2016-01-20  19.0  0.826354    High   96.640201

In [27]:
df.reindex(index=[0,2,5], columns=['A','C','B'])

A     C   B
0 2016-01-01  High NaN
2 2016-01-03   Low NaN
5 2016-01-06  High NaN

In [37]:
df1 = pd.DataFrame(np.random.randn(10,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(7,3),columns=['col1','col2','col3'])
df1

col1      col2      col3
0 -0.230721  0.449490  0.802328
1 -0.210581 -1.694493  1.102340
2  1.520002  0.398635 -0.537286
3 -0.882228 -1.486106 -1.086027
4 -0.189903 -0.003006 -1.638640
5  0.733368 -0.668368 -1.438615
6 -1.304508  1.384253  0.565223
7  0.406718 -0.951135  0.321198
8 -0.545230 -1.463538 -1.667084
9 -0.339355 -0.140370 -1.040927

In [38]:
df2

col1      col2      col3
0 -0.401951  0.182802 -0.943471
1 -0.434123  1.286058 -2.034215
2  1.263769 -0.028309  1.285806
3  1.095595  2.813459 -0.752928
4 -0.272548 -0.434814  1.064998
5  1.188458  0.787697  0.110422
6 -0.366797  1.471955 -1.739902

In [40]:
df2 = df2.reindex_like(df1)
df2

col1      col2      col3
0 -0.401951  0.182802 -0.943471
1 -0.434123  1.286058 -2.034215
2  1.263769 -0.028309  1.285806
3  1.095595  2.813459 -0.752928
4 -0.272548 -0.434814  1.064998
5  1.188458  0.787697  0.110422
6 -0.366797  1.471955 -1.739902
7       NaN       NaN       NaN
8       NaN       NaN       NaN
9       NaN       NaN       NaN

In [43]:
# filling while reindexing
df1 = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(2,3),columns=['col1','col2','col3'])
df1

col1      col2      col3
0 -1.612104  0.034553  0.383773
1 -0.019401 -1.039843  0.587234
2 -0.820116 -0.200297 -1.477645
3 -1.448518  0.159339 -1.109980
4  0.875320  0.472838 -0.774669
5  1.058070  0.057260  0.758742

In [42]:
df2

col1      col2      col3
0 -0.091622 -0.060937 -0.353105
1 -1.159541  1.062191  0.068164

In [44]:
# padding NAN's
df2.reindex_like(df1)

col1      col2      col3
0  1.137731 -2.463805 -0.645980
1 -1.394216 -0.985877 -0.503902
2       NaN       NaN       NaN
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN

In [48]:
# fill NAN's with preceding values
df2.reindex_like(df1, method='ffill') # ffill, bfill, nearest

col1      col2      col3
0  1.137731 -2.463805 -0.645980
1 -1.394216 -0.985877 -0.503902
2 -1.394216 -0.985877 -0.503902
3 -1.394216 -0.985877 -0.503902
4 -1.394216 -0.985877 -0.503902
5 -1.394216 -0.985877 -0.503902

In [50]:
# limits on filling while reindexing
# limit specifies the maximum count of consecutive matches
df2.reindex_like(df1, method='ffill', limit=1)

col1      col2      col3
0  1.137731 -2.463805 -0.645980
1 -1.394216 -0.985877 -0.503902
2 -1.394216 -0.985877 -0.503902
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN

In [51]:
# renaming
# relabel an axis based on some mapping
df1.rename(columns={'col1': 'c1', 'col2': 'c2', 'col3': 'c3'})

col1      col2      col3
0 -1.612104  0.034553  0.383773
1 -0.019401 -1.039843  0.587234
2 -0.820116 -0.200297 -1.477645
3 -1.448518  0.159339 -1.109980
4  0.875320  0.472838 -0.774669
5  1.058070  0.057260  0.758742