In [1]:
import pandas as pd
import numpy as np

In [3]:
# series: 1 dim (size immutable)
# dataframe: 2 dim
# panel: 3 dim

### Series ###

In [13]:
"""
pd.Series(data, index, dtype, copy)
    data: data takes various forms like ndarray, list, constants
    index: Index values must be unique and hashable, same length as data. 
           Default np.arrange(n) if no index is passed.
    dtype: dtype is for data type. If None, data type will be inferred
    copy: Copy data. Default False
"""
s = pd.Series(dtype=object)
s

Series([], dtype: object)

In [23]:
# from numpy array
data = np.array(['a', 'b', 'c', 'd'])
s = pd.Series(data)
print(s)
s = pd.Series(data, index=[100, 101, 102, 103])
print(s)

0    a
1    b
2    c
3    d
dtype: object
100    a
101    b
102    c
103    d
dtype: object


In [42]:
data = np.array([1.1, 2.2, 3.3, 4.4]) # ??? only affects np.array non string
s = pd.Series(data, copy=False)
s.iloc[0] = 10.2
print(s)
print(data)

0    10.2
1     2.2
2     3.3
3     4.4
dtype: float64
[10.2  2.2  3.3  4.4]


In [50]:
# from dictionary
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data) # keys are used to construct index
print(s)
s = pd.Series(data, index=['a', 'b', 'c', 'd']) # index order preserved
print(s)

a    0.0
b    1.0
c    2.0
dtype: float64
a    0.0
b    1.0
c    2.0
d    NaN
dtype: float64


In [52]:
# from scalar
s = pd.Series(5, index=[0, 1, 2, 3])
s # the value will be repeated to match the length of index

0    5
1    5
2    5
3    5
dtype: int64

In [58]:
# accessing data
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s[1])
print(s[:3])
print(s[-3:])
print(s['d'])
print(s[['a', 'c', 'd']])


2
a    1
b    2
c    3
dtype: int64
c    3
d    4
e    5
dtype: int64
4
a    1
c    3
d    4
dtype: int64


### DataFrame ###

In [2]:
''' 
pandas.DataFrame(data, index, columns, dtype, copy)
    data: ndarray, series, map, lists, dict, constants
    index: row labels
'''

' \npandas.DataFrame(data, index, columns, dtype, copy)\n    data: ndarray, series, map, lists, dict, constants\n    index: row labels\n'

In [6]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [12]:
# create df from list
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df) # deprecated

   0
0  1
1  2
2  3
3  4
4  5
     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13
     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


/Users/phichitchulanont/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3267: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)


In [13]:
# create df from Dict of ndarrays / Lists
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
df

Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42

In [20]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]} # each dic is a column
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
df

Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42

In [21]:
# create df from list of dicts
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}] # each dic is a row
df = pd.DataFrame(data)
df

a   b     c
0  1   2   NaN
1  5  10  20.0

In [22]:
# seet index
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, index=['first', 'second'])
df

a   b     c
first   1   2   NaN
second  5  10  20.0

In [24]:
# create df from Dic of Series
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [25]:
# select column
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [30]:
# column addition
df['three'] = df['one'] + df['two']
df

one  two  three
a  1.0    1    2.0
b  2.0    2    4.0
c  3.0    3    6.0
d  NaN    4    NaN

In [31]:
# column deletion
del df['three']
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [33]:
df.pop('two')
df

one
a  1.0
b  2.0
c  3.0
d  NaN

In [35]:
# row selection, addition, and deletion
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [41]:
print(type(df.loc['b']))
df.loc['b']

<class 'pandas.core.series.Series'>


one    2.0
two    2.0
Name: b, dtype: float64

In [42]:
df.iloc[2]

one    3.0
two    3.0
Name: c, dtype: float64

In [43]:
# slice rows
df[2:4]

one  two
c  3.0    3
d  NaN    4

In [12]:
# addition
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])
df = df.append(df2)
df

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [13]:
print(df.index)
df = df.drop(index=0)
print(df.index)
df

Int64Index([0, 1, 0, 1], dtype='int64')
Int64Index([1, 1], dtype='int64')


a  b
1  3  4
1  7  8

### Panel ###

In [19]:
print(pd.__version__)
# panel has been removed

1.3.1


In [ ]:
# pandas.Panel(data, items, major_axis, minor_axis, dtype, copy)
# deprecated

In [20]:
data = np.random.rand(2,4,5)
print(data)
#p = pd.Panel(data)

[[[0.88734208 0.06838684 0.85097435 0.06880823 0.50740681]
  [0.53391734 0.48904843 0.80451022 0.19523583 0.98792353]
  [0.88117797 0.96723983 0.57660127 0.86192481 0.89825808]
  [0.0839457  0.4874043  0.31584979 0.90837376 0.402868  ]]

 [[0.49019733 0.97867174 0.59028147 0.58462989 0.54630031]
  [0.56666222 0.70302267 0.05812085 0.88207743 0.48650731]
  [0.2712874  0.91200067 0.5440278  0.81565483 0.03874466]
  [0.91817501 0.35323288 0.79801686 0.24815126 0.23603052]]]


### Basic Functionality ###

In [2]:
s = pd.Series(np.random.randn(4))

In [5]:
print("axes\n", s.axes)
print("dtype\n", s.dtype)
print("empty\n", s.empty)
print("ndim\n", s.ndim)
print("size\n", s.size)
print("values\n", s.values)
print("head\n", s.head())
print("tail\n", s.tail())

axes
 [RangeIndex(start=0, stop=4, step=1)]
dtype
 float64
empty
 False
ndim
 1
size
 4
values
 [ 0.06504169 -1.02060985  0.21459751  0.70705839]
head
 0    0.065042
1   -1.020610
2    0.214598
3    0.707058
dtype: float64
tail
 0    0.065042
1   -1.020610
2    0.214598
3    0.707058
dtype: float64


In [9]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}
df = pd.DataFrame(d)
df.dtypes

Name       object
Age         int64
Rating    float64
dtype: object

In [10]:
df.T

0      1      2     3      4      5     6
Name     Tom  James  Ricky   Vin  Steve  Smith  Jack
Age       25     26     25    23     30     29    23
Rating  4.23   3.24   3.98  2.56    3.2    4.6   3.8

### Descriptive Statistics ###

In [11]:
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}

df = pd.DataFrame(d)

In [13]:
df.sum()

Name      TomJamesRickyVinSteveSmithJackLeeDavidGasperBe...
Age                                                     382
Rating                                                44.92
dtype: object

In [15]:
df.sum(axis=1, numeric_only=True)

0     29.23
1     29.24
2     28.98
3     25.56
4     33.20
5     33.60
6     26.80
7     37.78
8     42.98
9     34.80
10    55.10
11    49.65
dtype: float64

In [19]:
"""
count()
sum()
mean()
median()
mode()
std()
min()
max()
abs()
prod(): product of values
cumsum(): cumulative sum
cumprod(): cumulative product
"""

'\ncount()\nsum()\nmean()\nmedian()\nmode()\nstd()\nmin()\nmax()\nabs()\nprod(): product of values\ncumsum(): cumulative sum\ncumprod(): cumulative product\n'

In [23]:
# summarizing data
# df.describe() # excludes character column
df.describe(include=['object']) # just Name

Name
count    12
unique   12
top     Tom
freq      1

In [24]:
df.describe(include='all')

Name        Age     Rating
count    12  12.000000  12.000000
unique   12        NaN        NaN
top     Tom        NaN        NaN
freq      1        NaN        NaN
mean    NaN  31.833333   3.743333
std     NaN   9.232682   0.661628
min     NaN  23.000000   2.560000
25%     NaN  25.000000   3.230000
50%     NaN  29.500000   3.790000
75%     NaN  35.500000   4.132500
max     NaN  51.000000   4.800000

### Function Application ###

Table wise function application: pipe() <br>
Row or Column wise function application: apply() <br>
Element wise function application: applymap() <br>

In [6]:
# table-wise
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['col1','col2','col3'])
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [12]:
def adder(m, n, p):
    return m + n - p
df.pipe(adder, 2, 3)
#df.pipe(lambda x : x+2) # add 2 to each cell

col1  col2  col3
0     0     1     2
1     3     4     5
2     6     7     8

In [13]:
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [20]:
# row/column wise
# row: axis=1, column: axis=0
df.apply(np.mean) # mean of columns

col1    4.0
col2    5.0
col3    6.0
dtype: float64

In [16]:
df.apply(np.mean, axis=1) # mean of rows

0    2.0
1    5.0
2    8.0
dtype: float64

In [21]:
df.apply(lambda x : x.max() - x.min(), axis=1)

0    2
1    2
2    2
dtype: int64

In [23]:
# element-wise
df['col1'].map(str)

0    1
1    4
2    7
Name: col1, dtype: object

### Reindexing ###
Changes the row labels and columns labels. 

In [25]:
N=20

df = pd.DataFrame({
   'A': pd.date_range(start='2016-01-01',periods=N,freq='D'),
   'x': np.linspace(0,stop=N-1,num=N),
   'y': np.random.rand(N),
   'C': np.random.choice(['Low','Medium','High'],N).tolist(),
   'D': np.random.normal(100, 10, size=(N)).tolist()
})
df

A     x         y       C           D
0  2016-01-01   0.0  0.873822    High  103.361889
1  2016-01-02   1.0  0.416533  Medium  106.629000
2  2016-01-03   2.0  0.435559     Low   98.477243
3  2016-01-04   3.0  0.439431    High   96.107612
4  2016-01-05   4.0  0.481112     Low   99.827981
5  2016-01-06   5.0  0.154059    High  116.755378
6  2016-01-07   6.0  0.036748    High   82.744792
7  2016-01-08   7.0  0.392114     Low  111.885502
8  2016-01-09   8.0  0.716958  Medium  110.589856
9  2016-01-10   9.0  0.205751  Medium  113.043914
10 2016-01-11  10.0  0.322804    High  115.675756
11 2016-01-12  11.0  0.474384     Low  102.459813
12 2016-01-13  12.0  0.308507  Medium  100.142202
13 2016-01-14  13.0  0.828070  Medium   95.902893
14 2016-01-15  14.0  0.328733     Low  105.424876
15 2016-01-16  15.0  0.122427    High  110.136888
16 2016-01-17  16.0  0.527552    High   90.923405
17 2016-01-18  17.0  0.726843  Medium  111.709191
18 2016-01-19  18.0  0.894948    High   99.828281
19 2016-01-20  19.0  0.826354    High   96.640201

In [27]:
df.reindex(index=[0,2,5], columns=['A','C','B'])

A     C   B
0 2016-01-01  High NaN
2 2016-01-03   Low NaN
5 2016-01-06  High NaN

In [37]:
df1 = pd.DataFrame(np.random.randn(10,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(7,3),columns=['col1','col2','col3'])
df1

col1      col2      col3
0 -0.230721  0.449490  0.802328
1 -0.210581 -1.694493  1.102340
2  1.520002  0.398635 -0.537286
3 -0.882228 -1.486106 -1.086027
4 -0.189903 -0.003006 -1.638640
5  0.733368 -0.668368 -1.438615
6 -1.304508  1.384253  0.565223
7  0.406718 -0.951135  0.321198
8 -0.545230 -1.463538 -1.667084
9 -0.339355 -0.140370 -1.040927

In [38]:
df2

col1      col2      col3
0 -0.401951  0.182802 -0.943471
1 -0.434123  1.286058 -2.034215
2  1.263769 -0.028309  1.285806
3  1.095595  2.813459 -0.752928
4 -0.272548 -0.434814  1.064998
5  1.188458  0.787697  0.110422
6 -0.366797  1.471955 -1.739902

In [40]:
df2 = df2.reindex_like(df1)
df2

col1      col2      col3
0 -0.401951  0.182802 -0.943471
1 -0.434123  1.286058 -2.034215
2  1.263769 -0.028309  1.285806
3  1.095595  2.813459 -0.752928
4 -0.272548 -0.434814  1.064998
5  1.188458  0.787697  0.110422
6 -0.366797  1.471955 -1.739902
7       NaN       NaN       NaN
8       NaN       NaN       NaN
9       NaN       NaN       NaN

In [43]:
# filling while reindexing
df1 = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(2,3),columns=['col1','col2','col3'])
df1

col1      col2      col3
0 -1.612104  0.034553  0.383773
1 -0.019401 -1.039843  0.587234
2 -0.820116 -0.200297 -1.477645
3 -1.448518  0.159339 -1.109980
4  0.875320  0.472838 -0.774669
5  1.058070  0.057260  0.758742

In [42]:
df2

col1      col2      col3
0 -0.091622 -0.060937 -0.353105
1 -1.159541  1.062191  0.068164

In [44]:
# padding NAN's
df2.reindex_like(df1)

col1      col2      col3
0  1.137731 -2.463805 -0.645980
1 -1.394216 -0.985877 -0.503902
2       NaN       NaN       NaN
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN

In [48]:
# fill NAN's with preceding values
df2.reindex_like(df1, method='ffill') # ffill, bfill, nearest

col1      col2      col3
0  1.137731 -2.463805 -0.645980
1 -1.394216 -0.985877 -0.503902
2 -1.394216 -0.985877 -0.503902
3 -1.394216 -0.985877 -0.503902
4 -1.394216 -0.985877 -0.503902
5 -1.394216 -0.985877 -0.503902

In [50]:
# limits on filling while reindexing
# limit specifies the maximum count of consecutive matches
df2.reindex_like(df1, method='ffill', limit=1)

col1      col2      col3
0  1.137731 -2.463805 -0.645980
1 -1.394216 -0.985877 -0.503902
2 -1.394216 -0.985877 -0.503902
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN

In [51]:
# renaming
# relabel an axis based on some mapping
df1.rename(columns={'col1': 'c1', 'col2': 'c2', 'col3': 'c3'})

col1      col2      col3
0 -1.612104  0.034553  0.383773
1 -0.019401 -1.039843  0.587234
2 -0.820116 -0.200297 -1.477645
3 -1.448518  0.159339 -1.109980
4  0.875320  0.472838 -0.774669
5  1.058070  0.057260  0.758742

### Iteration ###

In [2]:
N=20
df = pd.DataFrame({
   'A': pd.date_range(start='2016-01-01',periods=N,freq='D'),
   'x': np.linspace(0,stop=N-1,num=N),
   'y': np.random.rand(N),
   'C': np.random.choice(['Low','Medium','High'],N).tolist(),
   'D': np.random.normal(100, 10, size=(N)).tolist()
})
df

A     x         y       C           D
0  2016-01-01   0.0  0.997636    High  116.846854
1  2016-01-02   1.0  0.742211    High  103.323212
2  2016-01-03   2.0  0.367136     Low   97.035271
3  2016-01-04   3.0  0.203614  Medium  106.932941
4  2016-01-05   4.0  0.597159    High   99.322264
5  2016-01-06   5.0  0.176876     Low  108.933828
6  2016-01-07   6.0  0.247967    High   82.252784
7  2016-01-08   7.0  0.595879     Low   94.770744
8  2016-01-09   8.0  0.697455    High  101.273279
9  2016-01-10   9.0  0.238437    High  112.929821
10 2016-01-11  10.0  0.040012    High  110.114673
11 2016-01-12  11.0  0.489235     Low  106.184291
12 2016-01-13  12.0  0.314594    High  117.934733
13 2016-01-14  13.0  0.589643  Medium   88.435999
14 2016-01-15  14.0  0.070716    High   94.289477
15 2016-01-16  15.0  0.139055    High  103.144688
16 2016-01-17  16.0  0.083590     Low   91.223955
17 2016-01-18  17.0  0.043945    High   93.770180
18 2016-01-19  18.0  0.422332    High   83.941705
19 2016-01-20  19.0  0.576937     Low  102.566706

In [6]:
# iterate over columns
for c in df:
    print(c)

A
x
y
C
D


iteritems(): to iterate over the (key, value) pairs <br>
iterrows(): iterate over the rows as (index, series) pairs <br>
itertuples(): iterate over the rows as nametuples <br>

In [10]:
# iteritems()
df = pd.DataFrame(np.random.randn(4,3),columns=['col1','col2','col3'])
for key,value in df.iteritems():
    print('key: ', key) # column name
    print('value: ', value) # column values as a series

key:  col1
value:  0   -1.046493
1   -0.813712
2    1.361762
3    1.117959
Name: col1, dtype: float64
key:  col2
value:  0   -1.243294
1   -1.393429
2   -0.246564
3    1.152395
Name: col2, dtype: float64
key:  col3
value:  0    0.687142
1   -1.848731
2   -0.549771
3    0.770860
Name: col3, dtype: float64


In [16]:
# itertuples()
for row in df.itertuples():
    print(row) # each row as a tuple

Pandas(Index=0, col1=-1.0464926037479187, col2=-1.2432935082497865, col3=0.6871417539490404)
Pandas(Index=1, col1=-0.8137115179444295, col2=-1.3934290851396, col3=-1.8487306223816236)
Pandas(Index=2, col1=1.361761566297648, col2=-0.24656387358106183, col3=-0.549771072703467)
Pandas(Index=3, col1=1.1179589795766225, col2=1.1523946917707837, col3=0.7708597506065848)


In [18]:
# iterrows()
for index, row in df.iterrows():
    print(row['col1']) # named

-1.0464926037479187
-0.8137115179444295
1.361761566297648
1.1179589795766225


Changes made in iterating will not reflect on the original copy.

### Sorting ###
Two types of sorting: <br>
- By label 
- By actual value

In [3]:
df = pd.DataFrame(np.random.randn(10,2),
                  index=[1,4,6,2,3,5,9,8,0,7],
                  columns=['col2','col1'])
df

col2      col1
1 -0.506336 -1.109153
4 -0.904558 -0.748847
6  0.747450  0.456013
2 -0.410751  0.758358
3 -1.162652 -0.823916
5 -0.533381 -0.747486
9 -0.246642 -0.552436
8 -0.817401  0.296816
0  0.882397  1.524415
7  0.002302 -0.175101

In [5]:
# sort by index
df.sort_index() 

col2      col1
0  0.882397  1.524415
1 -0.506336 -1.109153
2 -0.410751  0.758358
3 -1.162652 -0.823916
4 -0.904558 -0.748847
5 -0.533381 -0.747486
6  0.747450  0.456013
7  0.002302 -0.175101
8 -0.817401  0.296816
9 -0.246642 -0.552436

In [6]:
# sort by index descending
df.sort_index(ascending=False)

col2      col1
9 -0.246642 -0.552436
8 -0.817401  0.296816
7  0.002302 -0.175101
6  0.747450  0.456013
5 -0.533381 -0.747486
4 -0.904558 -0.748847
3 -1.162652 -0.823916
2 -0.410751  0.758358
1 -0.506336 -1.109153
0  0.882397  1.524415

In [7]:
# sort by column
df.sort_index(axis=1)

col1      col2
1 -1.109153 -0.506336
4 -0.748847 -0.904558
6  0.456013  0.747450
2  0.758358 -0.410751
3 -0.823916 -1.162652
5 -0.747486 -0.533381
9 -0.552436 -0.246642
8  0.296816 -0.817401
0  1.524415  0.882397
7 -0.175101  0.002302

In [8]:
# sort by values
df.sort_values(by='col1')

col2      col1
1 -0.506336 -1.109153
3 -1.162652 -0.823916
4 -0.904558 -0.748847
5 -0.533381 -0.747486
9 -0.246642 -0.552436
7  0.002302 -0.175101
8 -0.817401  0.296816
6  0.747450  0.456013
2 -0.410751  0.758358
0  0.882397  1.524415

In [13]:
# kind=mergesort/heapsort/quicksort
# mergesort is the only stable algorithm
df.sort_values(by=['col1', 'col2'], kind='mergesort').sort_index(axis=1)

col1      col2
1 -1.109153 -0.506336
3 -0.823916 -1.162652
4 -0.748847 -0.904558
5 -0.747486 -0.533381
9 -0.552436 -0.246642
7 -0.175101  0.002302
8  0.296816 -0.817401
6  0.456013  0.747450
2  0.758358 -0.410751
0  1.524415  0.882397

### Working with Text Data ###

In [14]:
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234','SteveSmith'])
s

0             Tom
1    William Rick
2            John
3         Alber@t
4             NaN
5            1234
6      SteveSmith
dtype: object

In [16]:
s.str.lower()

0             tom
1    william rick
2            john
3         alber@t
4             NaN
5            1234
6      stevesmith
dtype: object

In [18]:
s.str.upper()

0             TOM
1    WILLIAM RICK
2            JOHN
3         ALBER@T
4             NaN
5            1234
6      STEVESMITH
dtype: object

In [19]:
s.str.len()

0     3.0
1    12.0
2     4.0
3     7.0
4     NaN
5     4.0
6    10.0
dtype: float64

In [20]:
s.str.strip()

0             Tom
1    William Rick
2            John
3         Alber@t
4             NaN
5            1234
6      SteveSmith
dtype: object

In [22]:
s.str.cat(sep='_') # list equivalent of ' '.join(list)

'Tom_William Rick_John_Alber@t_1234_SteveSmith'

In [25]:
# one-hot encoding
s.str.get_dummies()

1234  Alber@t  John  SteveSmith  Tom  William Rick
0     0        0     0           0    1             0
1     0        0     0           0    0             1
2     0        0     1           0    0             0
3     0        1     0           0    0             0
4     0        0     0           0    0             0
5     1        0     0           0    0             0
6     0        0     0           1    0             0

In [26]:
s.str.contains(' ')

0    False
1     True
2    False
3    False
4      NaN
5    False
6    False
dtype: object

In [27]:
s.str.replace('e', '!')

0             Tom
1    William Rick
2            John
3         Alb!r@t
4             NaN
5            1234
6      St!v!Smith
dtype: object

In [28]:
s.str.repeat(2)

0                      TomTom
1    William RickWilliam Rick
2                    JohnJohn
3              Alber@tAlber@t
4                         NaN
5                    12341234
6        SteveSmithSteveSmith
dtype: object

In [31]:
s.str.count('m') # the number of 'm' in each string

0    1.0
1    1.0
2    0.0
3    0.0
4    NaN
5    0.0
6    1.0
dtype: float64

In [32]:
s.str.startswith('T')

0     True
1    False
2    False
3    False
4      NaN
5    False
6    False
dtype: object

In [33]:
s.str.endswith('t')

0    False
1    False
2    False
3     True
4      NaN
5    False
6    False
dtype: object

In [35]:
s.str.find('e') # find index of e in each string

0   -1.0
1   -1.0
2   -1.0
3    3.0
4    NaN
5   -1.0
6    2.0
dtype: float64

In [36]:
s.str.findall('e')

0        []
1        []
2        []
3       [e]
4       NaN
5        []
6    [e, e]
dtype: object

In [37]:
s.str.swapcase()

0             tOM
1    wILLIAM rICK
2            jOHN
3         aLBER@T
4             NaN
5            1234
6      sTEVEsMITH
dtype: object

In [38]:
s.str.islower()

0    False
1    False
2    False
3    False
4      NaN
5    False
6    False
dtype: object

In [39]:
s.str.isupper()

0    False
1    False
2    False
3    False
4      NaN
5    False
6    False
dtype: object

In [40]:
s.str.isnumeric()

0    False
1    False
2    False
3    False
4      NaN
5     True
6    False
dtype: object

### Options and Customization ###
Pandas provide API to customize some aspects of its behavior, display is being mostly used. <br>


In [3]:
# get_option
pd.get_option("display.max_rows")

60

In [4]:
# get_option
pd.get_option("display.max_columns")

20

In [6]:
# set_option(param, value)
pd.set_option("display.max_rows",80)
pd.get_option("display.max_rows")

80

In [8]:
pd.set_option("display.max_columns",30)
pd.get_option("display.max_columns")

30

In [9]:
# reset_option 
pd.reset_option("display.max_rows")
pd.get_option("display.max_rows")

60

In [10]:
# describe_option(param)
pd.describe_option("display.max_rows")

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]


In [11]:
# option_context()
with pd.option_context("display.max_rows",10):
    print(pd.get_option("display.max_rows"))
    print(pd.get_option("display.max_rows"))

10
10


Other parameters:
- display.expand_frame_repr
- display.max_colwidth
- display.precision

In [15]:
# display full cell
pd.set_option('display.max_colwidth', None)
pd.reset_option('display.max_colwidth')
pd.describe_option("display.max_colwidth")

display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]


### Indexing and Selecting Data ###
- .loc(): label based
- .iloc(): integer based
- .ix(): both label and integer based

In [2]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])
df

A         B         C         D
a -0.840482  0.796581  1.323886 -0.040750
b  1.289429  1.364356 -0.195820  0.708334
c  0.180172 -0.706817  0.162248  0.163455
d -0.631510 -0.202458  0.194505  2.123660
e  0.766006  1.228239 -0.971065 -0.747227
f -2.230061  0.567799  2.166116  0.398932
g -1.045332 -0.693155  1.430022  0.984341
h  0.331253 -0.652437 -1.652693 -0.618784

In [3]:
# loc
df.loc[:, 'A']

a   -0.840482
b    1.289429
c    0.180172
d   -0.631510
e    0.766006
f   -2.230061
g   -1.045332
h    0.331253
Name: A, dtype: float64

In [4]:
df.loc[:, ['A', 'C']]

A         C
a -0.840482  1.323886
b  1.289429 -0.195820
c  0.180172  0.162248
d -0.631510  0.194505
e  0.766006 -0.971065
f -2.230061  2.166116
g -1.045332  1.430022
h  0.331253 -1.652693

In [11]:
df.loc['a':'d']

A         B         C         D
a -0.840482  0.796581  1.323886 -0.040750
b  1.289429  1.364356 -0.195820  0.708334
c  0.180172 -0.706817  0.162248  0.163455
d -0.631510 -0.202458  0.194505  2.123660

In [9]:
df.loc[:, 'A':'D']

A         B         C         D
a -0.840482  0.796581  1.323886 -0.040750
b  1.289429  1.364356 -0.195820  0.708334
c  0.180172 -0.706817  0.162248  0.163455
d -0.631510 -0.202458  0.194505  2.123660
e  0.766006  1.228239 -0.971065 -0.747227
f -2.230061  0.567799  2.166116  0.398932
g -1.045332 -0.693155  1.430022  0.984341
h  0.331253 -0.652437 -1.652693 -0.618784

In [7]:
df.loc['a'] > 0

A    False
B     True
C     True
D    False
Name: a, dtype: bool

In [12]:
# iloc
df.iloc[:4]

A         B         C         D
a -0.840482  0.796581  1.323886 -0.040750
b  1.289429  1.364356 -0.195820  0.708334
c  0.180172 -0.706817  0.162248  0.163455
d -0.631510 -0.202458  0.194505  2.123660

In [13]:
df.iloc[1:5, 2:4]

C         D
b -0.195820  0.708334
c  0.162248  0.163455
d  0.194505  2.123660
e -0.971065 -0.747227

### Statistical Functions ###

In [13]:
# percent_change: compares every element to previous element
# and compute change percentage
s = pd.Series([1,2,3,4,5,4])
s.pct_change()

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.250000
5   -0.200000
dtype: float64

In [16]:
# covariance
# apply on series data, NA excluded automatically
s1 = pd.Series(np.random.randn(10))
s2 = pd.Series(np.random.randn(10))
s1.cov(s2)

0.2896923153795614

In [17]:
# when applied to dataframe, computes cov between all column pairs
df = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])
df.cov()

a         b         c         d         e
a  1.759315 -0.400468  0.013916 -0.171718  0.288688
b -0.400468  0.674302  0.468269  0.086660 -0.302967
c  0.013916  0.468269  1.078975  0.043207 -0.101756
d -0.171718  0.086660  0.043207  1.441158  0.360794
e  0.288688 -0.302967 -0.101756  0.360794  1.547692

In [19]:
# correlation
# shows the linear relationship between any two arrays of values
# pearson, spearman or kendall
df = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])
print(df['a'].corr(df['b']))
print(df.corr())

-0.4367276267085849
          a         b         c         d         e
a  1.000000 -0.436728  0.008017 -0.300905  0.150457
b -0.436728  1.000000  0.019321 -0.139295 -0.177913
c  0.008017  0.019321  1.000000 -0.226293 -0.041429
d -0.300905 -0.139295 -0.226293  1.000000 -0.147368
e  0.150457 -0.177913 -0.041429 -0.147368  1.000000


In [23]:
# data ranking
# produces ranking for each element in the array of elements
# in case of ties, assigns the mean rank
s = pd.Series(np.random.randn(5), index=list('abcde'))
s

a    0.138745
b   -1.863751
c   -0.578307
d   -1.740914
e    1.620804
dtype: float64

In [24]:
s.rank()

a    4.0
b    1.0
c    3.0
d    2.0
e    5.0
dtype: float64

In [25]:
# produce a tie
s['d'] = s['b']
s

a    0.138745
b   -1.863751
c   -0.578307
d   -1.863751
e    1.620804
dtype: float64

In [26]:
s.rank()

a    4.0
b    1.5
c    3.0
d    1.5
e    5.0
dtype: float64

In [31]:
s.rank(ascending=False)

a    2.0
b    4.5
c    3.0
d    4.5
e    1.0
dtype: float64

In [32]:
# tie-breaking methods:
# average, min, max, first
s.rank(method='dense')

a    3.0
b    1.0
c    2.0
d    1.0
e    4.0
dtype: float64

### Window Functions ###

In [2]:
df = pd.DataFrame(np.random.randn(10, 4),
   index = pd.date_range('1/1/2000', periods=10),
   columns = ['A', 'B', 'C', 'D'])
df

A         B         C         D
2000-01-01 -0.910785 -0.735043 -1.949817 -0.037263
2000-01-02  1.191521 -0.849860  0.800617 -0.291373
2000-01-03 -1.435357  0.857501  0.633571 -0.101477
2000-01-04 -0.629591 -1.180583  1.064422  0.039280
2000-01-05 -1.260367 -0.462698  0.868116 -1.493417
2000-01-06 -0.413815 -2.653404 -0.819452 -0.817764
2000-01-07  0.663473 -1.039580 -0.482105 -1.095395
2000-01-08  1.130393  1.431761 -0.159722  1.442843
2000-01-09 -1.600835  3.424895 -1.104637 -0.620516
2000-01-10 -0.569946  0.130006  1.365333  1.247728

In [3]:
# rolling(): can be applied to a series of data
df.rolling(window=3).mean()

A         B         C         D
2000-01-01       NaN       NaN       NaN       NaN
2000-01-02       NaN       NaN       NaN       NaN
2000-01-03 -0.384874 -0.242467 -0.171876 -0.143371
2000-01-04 -0.291142 -0.390981  0.832870 -0.117857
2000-01-05 -1.108438 -0.261926  0.855370 -0.518538
2000-01-06 -0.767924 -1.432228  0.371029 -0.757300
2000-01-07 -0.336903 -1.385227 -0.144480 -1.135525
2000-01-08  0.460017 -0.753741 -0.487093 -0.156772
2000-01-09  0.064343  1.272358 -0.582155 -0.091023
2000-01-10 -0.346796  1.662220  0.033658  0.690018

In [5]:
# expanding(): statistic with all the data up to that point
df.expanding(min_periods=3).mean()

A         B         C         D
2000-01-01       NaN       NaN       NaN       NaN
2000-01-02       NaN       NaN       NaN       NaN
2000-01-03 -0.384874 -0.242467 -0.171876 -0.143371
2000-01-04 -0.446053 -0.476996  0.137198 -0.097708
2000-01-05 -0.608916 -0.474137  0.283382 -0.376850
2000-01-06 -0.576399 -0.837348  0.099576 -0.450336
2000-01-07 -0.399274 -0.866238  0.016479 -0.542487
2000-01-08 -0.208066 -0.578988 -0.005546 -0.294321
2000-01-09 -0.362818 -0.134112 -0.127667 -0.330565
2000-01-10 -0.383531 -0.107701  0.021633 -0.172735

In [6]:
# ewm(): provides exponential weighted functions
#https://pandas.pydata.org/docs/user_guide/window.html#window-exponentially-weighted
df.ewm(com=0.5).mean()

A         B         C         D
2000-01-01 -0.910785 -0.735043 -1.949817 -0.037263
2000-01-02  0.665944 -0.821156  0.113009 -0.227845
2000-01-03 -0.788803  0.340991  0.473398 -0.140360
2000-01-04 -0.681335 -0.686071  0.872339 -0.019103
2000-01-05 -1.068951 -0.536540  0.869512 -1.006040
2000-01-06 -0.631594 -1.949721 -0.258010 -0.880350
2000-01-07  0.232179 -1.342683 -0.407475 -1.023779
2000-01-08  0.831079  0.507228 -0.242281  0.620886
2000-01-09 -0.790279  2.452438 -0.817214 -0.206757
2000-01-10 -0.643388  0.904124  0.637842  0.762916

### Aggregations
Once the rolling, expanding and ewm objects are created, several methods are available to perform aggregations on data.

In [11]:
r = df.rolling(window=3)
r

Rolling [window=3,center=False,axis=0,method=single]

In [12]:
r.aggregate(np.mean)

A         B         C         D
2000-01-01       NaN       NaN       NaN       NaN
2000-01-02       NaN       NaN       NaN       NaN
2000-01-03 -0.384874 -0.242467 -0.171876 -0.143371
2000-01-04 -0.291142 -0.390981  0.832870 -0.117857
2000-01-05 -1.108438 -0.261926  0.855370 -0.518538
2000-01-06 -0.767924 -1.432228  0.371029 -0.757300
2000-01-07 -0.336903 -1.385227 -0.144480 -1.135525
2000-01-08  0.460017 -0.753741 -0.487093 -0.156772
2000-01-09  0.064343  1.272358 -0.582155 -0.091023
2000-01-10 -0.346796  1.662220  0.033658  0.690018

### Missing Data

In [13]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f',
'h'],columns=['one', 'two', 'three'])
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df

one       two     three
a -0.281035 -1.073705 -0.350143
b       NaN       NaN       NaN
c  1.559960  0.118248 -0.020573
d       NaN       NaN       NaN
e  1.120297  0.595861 -0.151097
f -0.015159  0.212695 -0.038790
g       NaN       NaN       NaN
h  1.482952 -2.449178  0.985116

In [21]:
# check for missing values
df.isnull()

one    two  three
a  False  False  False
b   True   True   True
c  False  False  False
d   True   True   True
e  False  False  False
f  False  False  False
g   True   True   True
h  False  False  False

In [26]:
df[df['one'].notnull()]

one       two     three
a -0.281035 -1.073705 -0.350143
c  1.559960  0.118248 -0.020573
e  1.120297  0.595861 -0.151097
f -0.015159  0.212695 -0.038790
h  1.482952 -2.449178  0.985116

In [27]:
df['one'][df['one'].notnull()]

a   -0.281035
c    1.559960
e    1.120297
f   -0.015159
h    1.482952
Name: one, dtype: float64

In [30]:
df[df.notnull()] # doesn't work

one       two     three
a -0.281035 -1.073705 -0.350143
b       NaN       NaN       NaN
c  1.559960  0.118248 -0.020573
d       NaN       NaN       NaN
e  1.120297  0.595861 -0.151097
f -0.015159  0.212695 -0.038790
g       NaN       NaN       NaN
h  1.482952 -2.449178  0.985116

In [31]:
# calculations with missing data
df['one'].sum()

3.8670144001236713

In [33]:
# cleaning/filling missing data
# - Replace NaN with a scalar value, 0 for example
df = df.fillna(0)
df

one       two     three
a -0.281035 -1.073705 -0.350143
b  0.000000  0.000000  0.000000
c  1.559960  0.118248 -0.020573
d  0.000000  0.000000  0.000000
e  1.120297  0.595861 -0.151097
f -0.015159  0.212695 -0.038790
g  0.000000  0.000000  0.000000
h  1.482952 -2.449178  0.985116

In [35]:
# fill NaN forward/backward
# pad/fill: fill methods forward
# bfill/backfill: fill methods backward
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f',
'h'],columns=['one', 'two', 'three'])
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df

one       two     three
a  0.296128 -0.856496 -1.169845
b       NaN       NaN       NaN
c -1.103813  0.232597 -1.347229
d       NaN       NaN       NaN
e  1.826683  0.443762 -1.722320
f -1.115009  0.568330 -0.379339
g       NaN       NaN       NaN
h  2.085546 -0.818109 -1.691979

In [36]:
df.fillna('pad')

one       two     three
a  0.296128 -0.856496 -1.169845
b       pad       pad       pad
c -1.103813  0.232597 -1.347229
d       pad       pad       pad
e  1.826683  0.443762  -1.72232
f -1.115009   0.56833 -0.379339
g       pad       pad       pad
h  2.085546 -0.818109 -1.691979

In [38]:
df.fillna(method='backfill')

one       two     three
a  0.296128 -0.856496 -1.169845
b -1.103813  0.232597 -1.347229
c -1.103813  0.232597 -1.347229
d  1.826683  0.443762 -1.722320
e  1.826683  0.443762 -1.722320
f -1.115009  0.568330 -0.379339
g  2.085546 -0.818109 -1.691979
h  2.085546 -0.818109 -1.691979

In [39]:
# drop missing values
df.dropna()

one       two     three
a  0.296128 -0.856496 -1.169845
c -1.103813  0.232597 -1.347229
e  1.826683  0.443762 -1.722320
f -1.115009  0.568330 -0.379339
h  2.085546 -0.818109 -1.691979

In [40]:
# replace missing/generic values
df = pd.DataFrame({'one':[10,20,30,40,50,2000], 'two':[1000,0,30,40,50,60]})
df


one   two
0    10  1000
1    20     0
2    30    30
3    40    40
4    50    50
5  2000    60

In [41]:
df.replace({1000:10,2000:60})

one  two
0   10   10
1   20    0
2   30   30
3   40   40
4   50   50
5   60   60